### ISSUE TITLE
Wie steht ihr zum Verhältnis "Pfarrjugend" und "Junge Erwachsene"?

### ISSUE THREAD

**Issue by StefanBrand** [junge-pfarre/junge-pfarre.github.io#1]
Die beiden _(Alters-)Gruppen_ sind ja etwas abstrakt und klar abtrennen möcht ich die beiden sowieso nicht. Sollten sich auf der Webseite auf irgendeine Art Inhalte getrennt nach (Alters-)Gruppe finden, oder soll das eine Webseite nur für die Pfarrjugend sein?

Wenn die Webseite zwei (Alters-)Gruppen beherbergen soll, dann braucht sie einen Namen, der das repräsentiert.

**Comment by JojoRo10** [comment]
Wie wäre es wenn sie sich an beide Gruppen richtet und die Aktivitäten mit jeweils verschiedenen Farben getrennt werden? Name würde mir nur "Junge Pfarre" oder so was ähnliches einfallen;-)

**Comment by StefanBrand** [comment]
_Junge Pfarre_ hab ich mir auch schon gedacht. 😄

**Comment by StefanBrand** [comment]
Mittlerweile denke ich, dass wir gar keine Unterscheidung zwischen Jugendlichen und Jungen Erwachsenen brauchen. Ich denke, dass jeder Gefirmte mit uns feiern und beten kann, und der Heilige Geist die jungen Leute schon zu den Angeboten führen wird, die gerade passen.

**Comment by StefanBrand** [comment]
So, ich beschließe das jetzt einfach. 😉 Das ganze (bzw. *wir*) heißt (heißen) jetzt "Junge Pfarre". Und Junge Pfarre bedeutet Jugendliche ab 14 Jahren und Junge Erwachsene.
