### ISSUE TITLE
Text über Fahrgemeinschaft Jugendvigil Heiligenkreuz

### ISSUE THREAD

**Issue by StefanBrand** [junge-pfarre/junge-pfarre.github.io#10]

**Comment by JojoRo10** [comment]
# Fahrgemeinschaft zur Jugendvigil

Die Jugendvigil, am 1.Freitag des Monats im Stift Heiligenkreuz, ist etwas für ganz normale, coole Jugendliche ab der Firmung, die sich gemeinsam auf ein Abenteuer mit Gott einlassen wollen. Die Jugendvigil reißt Dich heraus aus dem Normalen, Langweiligen, aus dem was alle anderen tun!

Jedes Monat machen sich einige junge Leute auf den Weg, um dann gemeinsam zu singen, zu beten und mit Kerzen durch die mittelalterlichen Räume des Stiftes zu ziehen. 

Du bist gefirmt und offen für Neues?
Perfekt! - Dann komm doch einfach mal mit und lass dich - gemeinsam mit bis zu 200 anderen Jugendlichen - auf ein Abenteuer mit Gott ein.

_Für weitere Infos kannst du auch direkt auf der Homepage des Stiftes Heiligenkreuz vorbeischauen._
[](url)https://www.stift-heiligenkreuz.org/jugend-willkommen/jugendvigil/

**Comment by StefanBrand** [comment]
Sehr gut, danke! 

- http://jugendvigil.at verlinkt auf das Stift Heiligenkreuz. Wir könnten also direkt diese Internetadresse reinschreiben.
- Ich fänd noch eine Liste mit den Hardfacts auf einen Blick cool, analog zu #7

Was sagen die anderen?
