### ISSUE TITLE
Bibelteilen... bitte ausbessern falls Fehler drinnen sind!

### ISSUE THREAD

**Issue by xannaveronix** [junge-pfarre/junge-pfarre.github.io#18]
[Bibelteilen.docx](https://github.com/pfarrjugend-bnstst/pfarrjugend-bnstst.github.io/files/1674021/Bibelteilen.docx)

**Comment by StefanBrand** [comment]
Danke Anna! 🙂 Kopier den Text doch einfach als Kommentar in den bestehenden Issue: #9 .

**Comment by xannaveronix** [comment]
Bibelteilen
Beim Bibelteilen in unseren Jugendräumen der Frauenkirche beschäftigen wir uns genauer mit der heiligen Schrift.
Jeden zweiten Sonntag wird eine neue Textstelle ausgesucht, die wir dann gemeinsam durchlesen. Zusammen denken wir dann über diesen Text nach, tauschen uns gegenseitig aus und diskutieren über die Deutung und die Lehre von dieser Stelle.
Nach dem Abschlussgebet sitzen wir dann meistens noch gemeinsam in den Jugendräumen und genießen mit Spiel und Spaß den Abend.
