### ISSUE TITLE
Text über Bibelteilen

### ISSUE THREAD

**Issue by StefanBrand** [junge-pfarre/junge-pfarre.github.io#9]

**Comment by StefanBrand** [comment]
@xannaveronix hierher. 🙈 Und ein bisschen [Markdown](http://commonmark.org/help/) schadet auch nicht. 🙂

**Comment by xannaveronix** [comment]
# Bibelteilen
Beim Bibelteilen in unseren Jugendräumen der Frauenkirche beschäftigen wir uns genauer mit der **heiligen Schrift**. 
**Jeden zweiten Sonntag** wird eine neue Textstelle ausgesucht, die wir dann gemeinsam durchlesen. Zusammen denken wir dann über diesen Text nach, tauschen uns gegenseitig aus und diskutieren über die Deutung und die Lehre von dieser Stelle. 
Nach dem Abschlussgebet sitzen wir dann meistens noch gemeinsam in den Jugendräumen und genießen mit **Spiel und Spaß** den Abend.

**Comment by StefanBrand** [comment]
Beim Bibelteilen in unseren Jugendräumen der Frauenkirche beschäftigen wir uns genauer mit der heiligen Schrift.

Die Abendleitung sucht jedes Mal im Vorhinein eine Textstelle aus, die wir dann gemeinsam durchlesen. Zusammen denken wir dann über diesen Text nach, **tauschen uns gegenseitig aus** und diskutieren über die Deutung und die Lehre von dieser Stelle.

Nach dem Abschlussgebet sitzen wir dann meistens noch gemeinsam in den Jugendräumen und lassen **in gemütlicher Atmosphäre** den Abend ausklingen.

- Termin: Ca. 1x im Monat
- Uhrzeit: Beginn um 19:30
- Wo: In den Jugendräumen der Frauenkirche Baden
- Was brauche ich: Interesse an der Bibel und am gemeinsamen Austausch über das Wort Gottes

Wir freuen uns auf dich! :-)
___

Hab noch ein paar Änderungen vorgenommen. @xannaveronix Passt das für dich so? Wenn du noch Verbesserungsvorschläge hast, nur her damit! :)

Ps: Bibelteilen wird im kommenden Semester seltener stattfinden, weil wir ganz viele andere tolle Sachen vorhaben! 😄
